<?php

namespace Wurstpress\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
    public function getAllQuery()
    {
        return $this->createQueryBuilder('c')->getQuery();
    }
}
