<?php

namespace Wurstpress\CoreBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends NestedTreeRepository
{
}
