<?php

namespace Wurstpress\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function getPaginator($request, $entityManager)
    {
        $dql = "
        SELECT d,c
        FROM WurstpressCoreBundle:Document d
        JOIN d.collection c
        ";
        $query = $entityManager->createQuery($dql)
            ->setFirstResult($request->get('offset') ?: 0)
            ->setMaxResults($request->get('limit') ?: 100);

        return new Paginator($query, $fetchJoinCollection = true);
    }
}
