wurstpress_post:
    pattern:  /
    defaults: { _controller: "WurstpressCoreBundle:Post:index" }

wurstpress_post_show:
    pattern:  /{id}/show
    defaults: { _controller: "WurstpressCoreBundle:Post:show" }

wurstpress_post_new:
    pattern:  /new
    defaults: { _controller: "WurstpressCoreBundle:Post:new" }

wurstpress_post_create:
    pattern:  /create
    defaults: { _controller: "WurstpressCoreBundle:Post:create" }
    requirements: { _method: post }

wurstpress_post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "WurstpressCoreBundle:Post:edit" }

wurstpress_post_update:
    pattern:  /{id}/update
    defaults: { _controller: "WurstpressCoreBundle:Post:update" }
    requirements: { _method: post|put }

wurstpress_post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "WurstpressCoreBundle:Post:delete" }
    requirements: { _method: post|delete }
